### ISSUE TITLE
Crash When Installed on Server

### ISSUE THREAD

**Issue by Airisii** [OutrightWings/custom_horse_tack#1]
[crash-2024-01-08_16.28.50-fml.txt](https://github.com/OutrightWings/custom_horse_tack/files/13863815/crash-2024-01-08_16.28.50-fml.txt)

**Comment by OutrightWings** [comment]
Ah! Easy fix--Ill have that done within the day!

**Comment by OutrightWings** [comment]
I just uploaded a fixed version to Curseforge and Modrinth. Let me know if you still have any issues!

**Comment by Airisii** [comment]
Thank you! I'll let you know if any farther issues occur.
