### ISSUE TITLE
Crash on startup, graphical errors

### ISSUE THREAD

**Issue by DayTheMagpie** [OutrightWings/custom_horse_tack#2]
Version: 1.20.1
Loader: Forge

![image](https://github.com/OutrightWings/custom_horse_tack/assets/85978934/b584ef9c-2694-4539-a011-992011d94838)

Crash log: https://mclo.gs/yeGwfs4

Game crashes on startup, after game loads it takes you to what should be the crash screen but is the above image. Proceeding past this screen gives the same text graphical bug as seen below:

![image](https://github.com/OutrightWings/custom_horse_tack/assets/85978934/5047f6e7-e833-42d9-afac-70220c4901c8)

Attempting to load a world from here leads to the same crash. Uninstalling only this mod fixes the error.

**Comment by OutrightWings** [comment]
Oh dear! I do not immediately know what could be causing something like this. I have never had any issues like this in all my time bouncing between versions and loading my mod up with friends. I'll take a more in depth look at the log for details in a day or so.

**Comment by OutrightWings** [comment]
Wait! Do you not have Realistic Horse Genetics installed? That is an absolute requirement!!!

**Comment by DayTheMagpie** [comment]
Oop, looks like I don't! I installed through AT Launcher, it usually adds in the dependencies automatically. Might be that that isn't listed in a way Curseforge can detect? That seems to have fixed everything though, thank you very much!

**Comment by OutrightWings** [comment]
It's listed as a dependency, ATLauncher will let you install mods without dependencies if you go quick.
