### ISSUE TITLE
[BUG] Mixable Dye item data not always saving

### ISSUE THREAD

**Issue by Mnesikos** [OutrightWings/custom_horse_tack#3]
Minecraft 1.19.2, Forge 43.3.8, Custom horse tack 1.3.1, RHG 12.3

So far I've noticed two different instances of this, both while in creative mode:
- Middle-mouse clicking to copy the colored Mixable Dye item does not transfer the color data at all; if this is fixable it would help a ton to duplicate palettes!
- Randomly between crafting steps (DyeLeatherArmor tool as reference to get new colors), the Mixable Dye item that had color to it would reset when placed back in the crafting table directly from the crafting output. This happened to me only twice out of 5 different items all with 2-4 crafting steps. It did not continuously happen for the same recipe.

I am using a modpack, I don't expect the other mods to interact with any of this (*maybe* mouse tweaks, inventory essentials, and/or simple inventory sorter!), but let me know if you can't replicate it with just the base mod/s!

Fantastic work on this mod by the way, this is the first time I've been able to play around with it and I am super excited!! Absolutely love it.

**Comment by OutrightWings** [comment]
Having middle mouse copy data is probably very simple, just some little function I missed. I'll investigate. Mixed dye turning black.... I have a feeling I know what it is. Can you give me an example color where that happens? (Just the color I'll pull up it's steps with the leather armor tool). When it turns black, does the crafting output show it as black, or does it suddenly switch to it?

**Comment by Mnesikos** [comment]
Sorry, it doesn't turn black, it just resets to no color at all! It also doesn't happen to a specific color, it just (seemingly) randomly does it. I was able to recraft the same colors it originally happened to without the issue happening a second time. But! You could use hex #4C2666 to try to recreate it? It has 5 crafting steps, so I'd assume it'll be more likely to happen.

**Comment by OutrightWings** [comment]
So I can't replicate either of these things actually. When I middle click I do copy the color.

**Comment by Mnesikos** [comment]
Huh, okay! Maybe it is an incompatibility with one of the mods then.. I can try to do more testing to figure it out further.

Editing to say I just tested it with only the three mods I mentioned earlier (mouse tweaks, inventory essentials, and simple inventory sorter) and can't recreate it now either!! So I have no idea hahaha. Sorry about that. I'll keep messing around with it on our server and modpack; if I figure out anything more I'll definitely let you know, but it seems to not be an issue for you at least.
