### ISSUE TITLE
Compatibility with Horseshoes mod

### ISSUE THREAD

**Issue by M0l1bden** [OutrightWings/custom_horse_tack#4]
Is this mod compatible with Horseshoes mod?
modrinth.com/mod/horseshoes

**Comment by OutrightWings** [comment]
Whether or not horseshoes is compatible would be on the base mod Realistic Horse Genetics. Based on a cursory glance, the mod probably works with RHG? It all depends how they determine a horse mob. Whether they look at only the Horse class, or look at the parent AbstractHorse, which RHG horses stem from.
